version: "3.3"

services:
  nextjs:
    container_name: 'nextjs'
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - .env

  mongo:
    container_name: 'mongo'
    image: mongo:latest
    ports:
      - '127.0.0.1:27017:27017'
    environment:
      MONGO_USER: 'dev'
      MONGO_PASSWORD: 'password'
      MONGO_DB: 'emma-collecte'

  mongo-express:
    container_name: 'mongo-express'
    image: mongo-express
    ports:
      - '127.0.0.1:8081:8081'
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: 'admin'
#      ME_CONFIG_MONGODB_ADMINPASSWORD: 'password'
#      ME_CONFIG_MONGODB_SERVER: 'mongo'
    depends_on:
      - mongo
